export enum PARTITION_KEYS {
  COMMANDS = 'COMMANDS',
  HISTORIES = 'HISTORIES',
  COMMAND_TEMPLATE = 'COMMANDS_TEMPLATE',
  REQUESTS = 'REQUEST',
}

export enum REDIS_KEYS {
  COMMANDS = 'COMMANDS',
}