name: "Twitch Bot Enable/Disable"

on:
  workflow_dispatch:
    inputs:
      enabled:
        description: 'Enable bot'
        required: true
        default: "true"

jobs:
  enabled-disabled:
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
    steps:
      - uses: actions/checkout@v1
      - name: 'Install heroku'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - name: 'Heroku login credentials'
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: 'Enable bot'
        if:  ${{ github.event.inputs.enabled == 'true' }} 
        run: |
          echo 'Enable bot'
          heroku ps:scale worker=1 -a=cemdev-twitch-bot
      - name: 'Disable bot'
        if:  ${{ github.event.inputs.enabled == 'false' }} 
        run: |
          echo 'Disable bot'
          heroku ps:scale worker=0 -a=cemdev-twitch-bo


